# This is a basic workflow that is manually triggered

name: manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Name of the application to greet"
        # Default value if no value is explicitly provided
        default: "Alex"
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  init_manual_workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

      - name: install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install git-crypt

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: encrypt secrets
        run: |
          git-crypt unlock ./.crypt_key

      - name: encrypt secrets
        run: printf 'very_important => %s\n' "$very_important" > secrets/very_important.txt

      - name: decrypt secrets
        run: |
          git-crypt lock
