name: Android

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - "docs/**"
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
    tags:
      - v*
  repository_dispatch:
    types:
      - "test run"
      - "test::*"
  workflow_dispatch:
    inputs:
      brands:
        required: true
        default: '["Test1", "Test2", "Test3", "Test4", "Test5", "Test6"]'
      isShouldRunAnalysisBrands:
        required: true
        default: '["Test2"]'
      isShouldRunE2EBrands:
        required: true
        default: '["Test3"]'
env:
  DEFAULT_BRANDS: '["Test4"]'
  DEFAULT_IS_SHOULD_RUN_ANALYSIS_BRANDS: '["Test5"]'
  DEFAULT_IS_SHOULD_RUN_E2E_BRANDS: '["Test6"]'

jobs:
  brand-generate:
    runs-on: ubuntu-latest
    outputs:
      brands: ${{ steps.matrix-generate.outputs.brands }}
      isShouldRunAnalysisBrands: ${{ steps.matrix-generate.outputs.isShouldRunAnalysisBrands }}
      isShouldRunE2EBrands: ${{ steps.matrix-generate.outputs.isShouldRunE2EBrands }}
    steps:
      - name: Generate Matrix
        id: matrix-generate
        run: |
          brands='${{ github.event.client_payload.brands && toJSON(github.event.client_payload.brands) || inputs.brands  || env.DEFAULT_BRANDS}}'
          # echo "step brands => ${brands}"
          echo ::set-output name=brands::${brands}
          isShouldRunAnalysisBrands='${{ github.event.client_payload.isShouldRunAnalysisBrands && toJSON(github.event.client_payload.isShouldRunAnalysisBrands) || inputs.isShouldRunAnalysisBrands  || env.DEFAULT_IS_SHOULD_RUN_ANALYSIS_BRANDS}}'
          # echo "step isShouldRunAnalysisBrands => ${isShouldRunAnalysisBrands}"
          echo ::set-output name=isShouldRunAnalysisBrands::${isShouldRunAnalysisBrands}
          isShouldRunE2EBrands='${{ github.event.client_payload.isShouldRunE2EBrands && toJSON(github.event.client_payload.isShouldRunE2EBrands) || inputs.isShouldRunE2EBrands  || env.DEFAULT_IS_SHOULD_RUN_ANALYSIS_BRANDS}}'
          # echo "step isShouldRunE2EBrands => ${isShouldRunE2EBrands}"
          echo ::set-output name=isShouldRunE2EBrands::${isShouldRunE2EBrands}

  matrix-build:
    runs-on: ubuntu-latest
    needs: brand-generate
    strategy:
      matrix:
        brand: ${{ fromJSON(needs.brand-generate.outputs.brands) }}

    steps:
      - run: |
          echo 'brand => ${{ matrix.brand }}'
          echo 'AnalysisBrands => ${{ needs.brand-generate.outputs.isShouldRunAnalysisBrands }}'
          echo 'isShouldRunAnalysisBrands => ${{ contains(fromJSON(needs.brand-generate.outputs.isShouldRunAnalysisBrands), matrix.brand) }}'
      - name: Analysis
        if: contains(fromJSON(needs.brand-generate.outputs.isShouldRunAnalysisBrands), matrix.brand)
        run: |
          echo 'Analysis brand => ${{ matrix.brand }}'
      - name: build
        run: |
          echo 'build brand => ${{ matrix.brand }}'
          echo 'refs/tags/v => ${{ github.ref }}'
          echo 'version_name => ${GITHUB_REF#refs/tags/v}'
          echo 'version_number => ${(expr 1000 + $GITHUB_RUN_NUMBER)}'
          echo 'is Prod Release ${{ startsWith(github.ref, 'refs/tags/v') }}'
      - name: e2e
        if: contains(fromJSON(needs.brand-generate.outputs.isShouldRunE2EBrands), matrix.brand)
        run: |
          echo 'e2e brand => ${{ matrix.brand }}'
